### ISSUE TITLE
can it extract all the center lines?

### ISSUE THREAD

**Issue by qiang-zhang-neu** [pangyuteng/simple-centerline-extraction#1]
This is a very good project. However, I wonder whether it possible to extract all the center lines in one time rather than specify the start and end point. The skimage.morphology.skeletonize provide a skeletonization method, however, it may generate some wrong branches. 
Do you have any suggestion?

**Comment by pangyuteng** [comment]
I think your thinking is on the right track, google some more for inspirations, below link seems relevant to what you are asking.  If you are still stuck, try asking a detailed question over at stackoverflow. Good luck!
Https://github.com/Image-Py/sknw/blob/master/README.md

**Comment by qiang-zhang-neu** [comment]
> I think your thinking is on the right track, google some more for inspirations, below link seems relevant to what you are asking. If you are still stuck, try asking a detailed question over at stackoverflow. Good luck!
> [Https://github.com/Image-Py/sknw/blob/master/README.md](Https://github.com/Image-Py/sknw/blob/master/README.md)

Thank you for reply. The sknw is used to build graph for the reuslt of skimage.morphology.skeletonize. However, the reuslt of skimage.skeletonize is not smooth, and there are some wrong branch. What I want are all the extracted smooth center lines.
